#!/bin/sh
echo '222'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "develop" ]; then
    git tag -a "merge-$(date +%Y%m%d%H%M%S)" -m "Merge to develop"
    git push --tags
fi

echo '111'